eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
spring:
  application:
    name: orderServer
  datasource:
    url: jdbc:mysql://localhost:3306/weixin?useUnicode=true&useSSL=true&serverTimezone=CTT
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: macbeth
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
